### ISSUE TITLE
Ошибка загрузки модели под Win

### ISSUE THREAD

**Issue by Koziev** [ltgoslo/simple_elmo#3]
Добрый день,

при загрузке ELMO модели (немного доработанный get_elmo_vectors.py) в анаконде под Win с python 3.7.1 столкнулся с ошибкой в [строке bilm/data.py:29](https://github.com/ltgoslo/simple_elmo/blob/master/bilm/data.py#L29)

```
Traceback (most recent call last):
  File "run_elmo1.py", line 17, in <module>
    batcher, sentence_character_ids, elmo_sentence_input = load_elmo_embeddings(elmo_dir)
  File "E:\github\simple_elmo\elmo_helpers.py", line 81, in load_elmo_embeddings
    batcher = Batcher(vocab_file, 50)
  File "E:\github\simple_elmo\bilm\data.py", line 207, in __init__
    lm_vocab_file, max_token_length
  File "E:\github\simple_elmo\bilm\data.py", line 118, in __init__
    super(UnicodeCharsVocabulary, self).__init__(filename, **kwargs)
  File "E:\github\simple_elmo\bilm\data.py", line 29, in __init__
    for line in f:
  File "C:\Users\eek\Anaconda3\envs\tf21\lib\encodings\cp1251.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 300: character maps to <undefined>
```

После добавления руками encoding='utf-8' в вызове open() в [строке 27](https://github.com/ltgoslo/simple_elmo/blob/master/bilm/data.py#L29) модель загрузилась и отработал инференс.

**Comment by akutuzov** [comment]
Indeed, the code assumes that the system locale and the training corpus encoding are the same (most probably UTF-8, as this is also the default encoding for Python 3).
It is a pity that Windows, seemingly, still sticks with the outdated CP1251 encoding for Russian.

However, I don't feel this is an issue with the `simple_elmo` itself. You will have the same problem with any other Python 3 code trying to read from a UTF-8 text file. I would advise changing the system locale to UTF-8 (not sure whether this is possible in Windows) or switching to another OS.
Or, of course, it is possible to manually add the encoding statement to all `open()` calls in all the scripts you use.
