### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '*\options.json'

### ISSUE THREAD

**Issue by nassera2014** [ltgoslo/simple_elmo#7]
Hi, Thank you for your great job, i installed simple-elmo and I downloaded arabic model; and after I run this line : 
`from simple_elmo import ElmoModel

model = ElmoModel()
model.load("*/136")
model.get_elmo_vectors(sents)`

I  get this error : 
`FileNotFoundError: [Errno 2] No such file or directory: 'C:/Users/admin/Desktop/Data/136\\options.json'`

Thank you.

**Comment by akutuzov** [comment]
Hi,
Where did this model come from?
Is it a model from the ELMoForMAnyLangs project? Then you cannot use it with `simple_elmo`, see https://github.com/ltgoslo/simple_elmo#can-i-load-elmoformanylangs-models

**Comment by nassera2014** [comment]
I downloaded arabic model; from this page : http://vectors.nlpl.eu/repository/#

**Comment by akutuzov** [comment]
Yes, this is a model from the the ELMoForMAnyLangs project; see the `meta.json` file in the ZIP archive.
It can't be used with `simple_elmo`, unfortunately.
